// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: categoriamusical_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Musapi.Grpc
{
    public static partial class CategoriaMusicalService
    {
        static readonly string __ServiceName = "musapi.grpc.CategoriaMusicalService";

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
        {
#if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
            if (message is global::Google.Protobuf.IBufferMessage)
            {
                context.SetPayloadLength(message.CalculateSize());
                global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
                context.Complete();
                return;
            }
#endif
            context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static class __Helper_MessageCache<T>
        {
            public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
        {
#if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
            if (__Helper_MessageCache<T>.IsBufferMessage)
            {
                return parser.ParseFrom(context.PayloadAsReadOnlySequence());
            }
#endif
            return parser.ParseFrom(context.PayloadAsNewBuffer());
        }

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Musapi.Grpc.CategoriaMusicalRequest> __Marshaller_musapi_grpc_CategoriaMusicalRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Musapi.Grpc.CategoriaMusicalRequest.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Musapi.Grpc.CategoriaMusicalResponse> __Marshaller_musapi_grpc_CategoriaMusicalResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Musapi.Grpc.CategoriaMusicalResponse.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Musapi.Grpc.Empty> __Marshaller_musapi_grpc_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Musapi.Grpc.Empty.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Musapi.Grpc.CategoriaMusicalListResponse> __Marshaller_musapi_grpc_CategoriaMusicalListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Musapi.Grpc.CategoriaMusicalListResponse.Parser));
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Marshaller<global::Musapi.Grpc.CategoriaMusicalEditRequest> __Marshaller_musapi_grpc_CategoriaMusicalEditRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Musapi.Grpc.CategoriaMusicalEditRequest.Parser));

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Musapi.Grpc.CategoriaMusicalRequest, global::Musapi.Grpc.CategoriaMusicalResponse> __Method_RegistrarCategoriaMusical = new grpc::Method<global::Musapi.Grpc.CategoriaMusicalRequest, global::Musapi.Grpc.CategoriaMusicalResponse>(
            grpc::MethodType.Unary,
            __ServiceName,
            "RegistrarCategoriaMusical",
            __Marshaller_musapi_grpc_CategoriaMusicalRequest,
            __Marshaller_musapi_grpc_CategoriaMusicalResponse);

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Musapi.Grpc.Empty, global::Musapi.Grpc.CategoriaMusicalListResponse> __Method_ObtenerCategoriasMusicales = new grpc::Method<global::Musapi.Grpc.Empty, global::Musapi.Grpc.CategoriaMusicalListResponse>(
            grpc::MethodType.Unary,
            __ServiceName,
            "ObtenerCategoriasMusicales",
            __Marshaller_musapi_grpc_Empty,
            __Marshaller_musapi_grpc_CategoriaMusicalListResponse);

        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        static readonly grpc::Method<global::Musapi.Grpc.CategoriaMusicalEditRequest, global::Musapi.Grpc.CategoriaMusicalResponse> __Method_EditarCategoriaMusical = new grpc::Method<global::Musapi.Grpc.CategoriaMusicalEditRequest, global::Musapi.Grpc.CategoriaMusicalResponse>(
            grpc::MethodType.Unary,
            __ServiceName,
            "EditarCategoriaMusical",
            __Marshaller_musapi_grpc_CategoriaMusicalEditRequest,
            __Marshaller_musapi_grpc_CategoriaMusicalResponse);

        /// <summary>Service descriptor</summary>
        public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
        {
            get { return global::Musapi.Grpc.CategoriamusicalServiceReflection.Descriptor.Services[0]; }
        }

        /// <summary>Base class for server-side implementations of CategoriaMusicalService</summary>
        [grpc::BindServiceMethod(typeof(CategoriaMusicalService), "BindService")]
        public abstract partial class CategoriaMusicalServiceBase
        {
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::System.Threading.Tasks.Task<global::Musapi.Grpc.CategoriaMusicalResponse> RegistrarCategoriaMusical(global::Musapi.Grpc.CategoriaMusicalRequest request, grpc::ServerCallContext context)
            {
                throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
            }

            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::System.Threading.Tasks.Task<global::Musapi.Grpc.CategoriaMusicalListResponse> ObtenerCategoriasMusicales(global::Musapi.Grpc.Empty request, grpc::ServerCallContext context)
            {
                throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
            }

            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::System.Threading.Tasks.Task<global::Musapi.Grpc.CategoriaMusicalResponse> EditarCategoriaMusical(global::Musapi.Grpc.CategoriaMusicalEditRequest request, grpc::ServerCallContext context)
            {
                throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
            }

        }

        /// <summary>Client for CategoriaMusicalService</summary>
        public partial class CategoriaMusicalServiceClient : grpc::ClientBase<CategoriaMusicalServiceClient>
        {
            /// <summary>Creates a new client for CategoriaMusicalService</summary>
            /// <param name="channel">The channel to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public CategoriaMusicalServiceClient(grpc::ChannelBase channel) : base(channel)
            {
            }
            /// <summary>Creates a new client for CategoriaMusicalService that uses a custom <c>CallInvoker</c>.</summary>
            /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public CategoriaMusicalServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
            {
            }
            /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected CategoriaMusicalServiceClient() : base()
            {
            }
            /// <summary>Protected constructor to allow creation of configured clients.</summary>
            /// <param name="configuration">The client configuration.</param>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected CategoriaMusicalServiceClient(ClientBaseConfiguration configuration) : base(configuration)
            {
            }

            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Musapi.Grpc.CategoriaMusicalResponse RegistrarCategoriaMusical(global::Musapi.Grpc.CategoriaMusicalRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return RegistrarCategoriaMusical(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Musapi.Grpc.CategoriaMusicalResponse RegistrarCategoriaMusical(global::Musapi.Grpc.CategoriaMusicalRequest request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_RegistrarCategoriaMusical, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Musapi.Grpc.CategoriaMusicalResponse> RegistrarCategoriaMusicalAsync(global::Musapi.Grpc.CategoriaMusicalRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return RegistrarCategoriaMusicalAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Musapi.Grpc.CategoriaMusicalResponse> RegistrarCategoriaMusicalAsync(global::Musapi.Grpc.CategoriaMusicalRequest request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_RegistrarCategoriaMusical, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Musapi.Grpc.CategoriaMusicalListResponse ObtenerCategoriasMusicales(global::Musapi.Grpc.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return ObtenerCategoriasMusicales(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Musapi.Grpc.CategoriaMusicalListResponse ObtenerCategoriasMusicales(global::Musapi.Grpc.Empty request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_ObtenerCategoriasMusicales, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Musapi.Grpc.CategoriaMusicalListResponse> ObtenerCategoriasMusicalesAsync(global::Musapi.Grpc.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return ObtenerCategoriasMusicalesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Musapi.Grpc.CategoriaMusicalListResponse> ObtenerCategoriasMusicalesAsync(global::Musapi.Grpc.Empty request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_ObtenerCategoriasMusicales, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Musapi.Grpc.CategoriaMusicalResponse EditarCategoriaMusical(global::Musapi.Grpc.CategoriaMusicalEditRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return EditarCategoriaMusical(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual global::Musapi.Grpc.CategoriaMusicalResponse EditarCategoriaMusical(global::Musapi.Grpc.CategoriaMusicalEditRequest request, grpc::CallOptions options)
            {
                return CallInvoker.BlockingUnaryCall(__Method_EditarCategoriaMusical, null, options, request);
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Musapi.Grpc.CategoriaMusicalResponse> EditarCategoriaMusicalAsync(global::Musapi.Grpc.CategoriaMusicalEditRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
            {
                return EditarCategoriaMusicalAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
            }
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            public virtual grpc::AsyncUnaryCall<global::Musapi.Grpc.CategoriaMusicalResponse> EditarCategoriaMusicalAsync(global::Musapi.Grpc.CategoriaMusicalEditRequest request, grpc::CallOptions options)
            {
                return CallInvoker.AsyncUnaryCall(__Method_EditarCategoriaMusical, null, options, request);
            }
            /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
            protected override CategoriaMusicalServiceClient NewInstance(ClientBaseConfiguration configuration)
            {
                return new CategoriaMusicalServiceClient(configuration);
            }
        }

        /// <summary>Creates service definition that can be registered with a server</summary>
        /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public static grpc::ServerServiceDefinition BindService(CategoriaMusicalServiceBase serviceImpl)
        {
            return grpc::ServerServiceDefinition.CreateBuilder()
                .AddMethod(__Method_RegistrarCategoriaMusical, serviceImpl.RegistrarCategoriaMusical)
                .AddMethod(__Method_ObtenerCategoriasMusicales, serviceImpl.ObtenerCategoriasMusicales)
                .AddMethod(__Method_EditarCategoriaMusical, serviceImpl.EditarCategoriaMusical).Build();
        }

        /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
        /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
        /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
        /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
        public static void BindService(grpc::ServiceBinderBase serviceBinder, CategoriaMusicalServiceBase serviceImpl)
        {
            serviceBinder.AddMethod(__Method_RegistrarCategoriaMusical, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Musapi.Grpc.CategoriaMusicalRequest, global::Musapi.Grpc.CategoriaMusicalResponse>(serviceImpl.RegistrarCategoriaMusical));
            serviceBinder.AddMethod(__Method_ObtenerCategoriasMusicales, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Musapi.Grpc.Empty, global::Musapi.Grpc.CategoriaMusicalListResponse>(serviceImpl.ObtenerCategoriasMusicales));
            serviceBinder.AddMethod(__Method_EditarCategoriaMusical, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Musapi.Grpc.CategoriaMusicalEditRequest, global::Musapi.Grpc.CategoriaMusicalResponse>(serviceImpl.EditarCategoriaMusical));
        }

    }
}
#endregion

